/*
https://www.codingninjas.com/studio/problems/ans-of-string_985087?interviewProblemRedirection=true
 ans of String
Moderate
0/80
Average time to solve is 15m
Contributed by
186 upvotes
Asked in companies
Problem statement
You are given a string 'STR' containing lowercase English letters from a to z inclusive. Your task is to find all non-empty possible ans of 'STR'.

A Subsequence of a string is the one which is generated by deleting 0 or more letters from the string and keeping the rest of the letters in the same order.
Detailed explanation ( Input/otpt format, Notes, Images )
Constraints:
1 <= T <= 10
1 <=  |STR| <= 16

Where |STR| represents the length of the string 'STR'.

Time Limit: 1 sec
Sample Input 1:
1
abc
Sample otpt 1:
a ab abc ac b bc c
Explanation of sample input 1:
All possible ans of abc are :
“a” , “b” , “c” , “ab” , “bc” , “ac”, “abc”
Sample Input 2:
1
bbb
Sample otpt 2:
b b b bb bb bb bbb
*/

#include <iostream>
#include <vector>
using namespace std;

void solve(string str, vector<string> &ans, int idx, string otpt)
{
        // base case
        if (idx > str.size())
        {
                if (otpt.length() > 0)
                        ans.push_back(otpt);
                return;
        }

        // exclusive
        solve(str, ans, idx + 1, otpt);

        // Inclusive
        otpt.push_back(str[idx]);
        solve(str, ans, idx + 1, otpt);
}

vector<string> subsequences(string str)
{
        int idx = 0;
        vector<string> ans;
        string otpt;
        solve(str, ans, idx, otpt);
        return ans;
}